server:
  port: ${NOMAD_HOST_PORT_http:8090}
  
spring:
  application:
    name: caller-service
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        register: false